export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SERVER_REPONSE_ERROR = 'LOGIN_USER_SERVER_REPONSE_ERROR';
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS = 'LOGIN_USER_SERVER_RESPONSE_SUCCESS';

export const SERVER_CALL_FAILED = 'SERVER_CALL_FAILED';

export const LOGOUT_USER  = 'LOGOUT_USER';
export const LOGOUT_USER_SERVER_RESPONSE_SUCCESS = 'LOGOUT_USER_SERVER_RESPONSE_SUCCESS';
export const SERVER_REPONSE_ERROR = 'SERVER_REPONSE_ERROR';
export const LOGOUT_USER_SERVER_REPONSE_ERROR = 'LOGOUT_USER_SERVER_REPONSE_ERROR';

export const VALIDATE_TOKEN = "VALIDATE_TOKEN";
export const VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS = "VALIDATE_TOKEN_SERVER_RESPONSE_SUCCESS";
export const VALIDATE_TOKEN_SERVER_REPONSE_ERROR = "VALIDATE_TOKEN_SERVER_REPONSE_ERROR";
export const VALIDATE_TOKEN_SERVER_CALL_FAILED = "VALIDATE_TOKEN_SERVER_CALL_FAILED";
export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';


// firebase database related 

export const SIGNUP_SAVE_DATABASE = "SIGNUP_SAVE_DATABASE";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Employee firebase database related 

export const EMPLOYEE_SAVE_DATABASE = "EMPLOYEE_SAVE_DATABASE";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Get Data from Employee Firebase

export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_LIST_SUCCESS_RESPONSE = "GET_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_UPDATED_EMPLOYEE_LIST_SUCCESS_RESPONSE = "GET_UPDATED_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_EMPLOYEE_LIST_ERROR_RESPONSE = "GET_EMPLOYEE_LIST_ERROR_RESPONSE";

// CREATE_TASK firebase database related 

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SERVER_RESPONSE_SUCCESS = "CREATE_TASK_SERVER_RESPONSE_SUCCESS";
export const CREATE_TASK_SERVER_RESPONSE_ERROR = "CREATE_TASK_SERVER_RESPONSE_ERROR";

// Task Details
export const GET_TASK_BY_EMPID = "GET_TASK_BY_EMPID";

// TASK DETAILS firebase database related 

export const TASK_DETAILS_SAVE_DATABASE = "TASK_DETAILS_SAVE_DATABASE";
export const TASK_DETAILS_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS = "TASK_DETAILS_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const TASK_DETAILS_SAVE_DATABASE_SERVER_RESPONSE_ERROR = "TASK_DETAILS_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

// Get Data from TaskDetails Firebase

export const GET_TASK_DETAILS = "GET_TASK_DETAILS";
export const GET_TASK_DETAILS_SUCCESS_RESPONSE = "GET_TASK_DETAILS_SUCCESS_RESPONSE";
export const GET_TASK_DETAILS_ERROR_RESPONSE = "GET_TASK_DETAILS_ERROR_RESPONSE";